Release version v1.0.7

diff --git a/src/agent b/src/agent
--- a/src/agent
+++ b/src/agent
@@ -143,22 +143,21 @@ send_json_to_api() {
     local http_code=1
 
     while [ $retry_count -lt $max_retries ]; do
-        (
+        spinner
+        while IFS= read -r line; do
+            parse_incoming_line "$line" #|| break
+        done < <(
         # mkfifo myfifo  # Create a named pipe (FIFO)
         # trap "rm -f myfifo" EXIT  # Ensure cleanup
-        spinner
         curl -sS --no-buffer -X POST "$model_endpoint" \
         -H "Content-Type: application/json" \
         -H "Authorization: Bearer $OPENROUTER_API_KEY" \
-        -w "\nCODE: %{http_code}\n" -d "$content" | while IFS= read -r line; do
-            parse_incoming_line "$line" #|| break
-        done
-        )  || http_code=$?
-        
-        handle_http_code $http_code
-        return_or_retry="$?"
-        [[ $return_or_retry -eq 2 ]] && continue
-        return $return_or_retry
+        -w "\nCODE: %{http_code}\n" -d "$content")  
+
+        # handle_http_code $http_code
+        # return_or_retry="$?"
+        # [[ $return_or_retry -eq 2 ]] && continue
+        # return $return_or_retry
     done
 }
 
