.

diff --git a/src/config b/src/config
--- a/src/config
+++ b/src/config
@@ -1,20 +1,34 @@
-VERSION="v1.0.1"
+VERSION="v1.0.0"
 REPO="doryashar/terminal-assistant"
 DEBUG=1
-AUTO_UPDATE=1
 EXEC_NAME="ai"
 INSTALL_DIR="$HOME/.local/bin"
 CONFIG_DIR="$HOME/.config/"
 CONFIG_FILE="${EXEC_NAME}.conf"
 
 create_config() {
+    # if config dir not exists, create it
+    if [ ! -d "$CONFIG_DIR" ]; then
+        mkdir -p "$CONFIG_DIR"
+        if [ $? -ne 0 ]; then
+            error "Failed to create config directory: $CONFIG_DIR"
+            exit 1
+        fi
+    fi
+
     # Create the config file
     cat <<EOF > "$CONFIG_DIR/$CONFIG_FILE"
     {
-    "auto_update": true
+        "auto_update": "false"
     }
 EOF
-    debug "Created config: $CONFIG_DIR/$CONFIG_FILE"
+    # if failed, exit
+    if [ $? -ne 0 ]; then
+        error "Failed to create config file: $CONFIG_DIR/$CONFIG_FILE"
+        exit 1
+    fi
+
+    info "Created config: $CONFIG_DIR/$CONFIG_FILE"
 }
 
 load_config() {
